version: '3'
services:
  app: 
    image: todo-app 
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3005
